### ISSUE TITLE
Portfinder breaking new Ember projects

### ISSUE THREAD

**Issue by rodrigoyoshida** [http-party/node-portfinder#88] opened 2019-08-19 03:35 UTC
According to the issue reported below, the latest portfinder version (1.0.22) might has a bug that breaks new Ember projects. That prevents people from serving their projects locally. Since I am not sure if it is an issue related to Ember our portfinder I am trying to report here to get some help. 

https://discuss.emberjs.com/t/port-4200-is-already-in-use/16972/3

**Comment by danlynn** [comment] 2019-08-19 03:39
This is why I posted this issue a few minutes ago:  https://github.com/http-party/node-portfinder/issues/87

**Comment by jelhan** [comment] 2019-08-19 12:49
@rodrigoyoshida This is tracked here: https://github.com/ember-cli/ember-cli/issues/8794 It's caused by #84 and #85.

**Comment by eriktrom** [comment] 2019-08-19 20:23
this should be fixed, i reverted npm deploy from sat morning

**Closed by eriktrom** 2019-08-19 20:23 UTC
